spring.application.name=colegio-disciplina

spring.data.mongodb.uri=mongodb://localhost:27017/colegio_disciplina

server.port=8080
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB